# .travis.yml

dist: bionic

jobs:
  include:
    - name: Lua 5.1
      env: LUA_APT=lua5.1

before_install:
  - sudo apt-get update
  - sudo apt-get -y install $LUA_APT luarocks

install:
  - sudo luarocks install busted
  - sudo luarocks install luacov

script:
  - busted -c test/*
  - luacov -cluacov.cfg

after_success:
  - bash <(curl -s https://codecov.io/bash)
